name: Sync Team Development to Company

on:
  push:
    branches:
      - development

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Team Repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push development to Company Repository
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git push https://x-access-token:${PAT_TOKEN}@github.com/SiddhikaShukla25/siddhika-task6.git HEAD:development
